### ISSUE TITLE
it wont generate Excavatable Surface (stone ore) if i use repair turret to build

### ISSUE THREAD

**Issue by CatAndHorse** [jurgyy/Factorio-Canal-Excavator#2]

**Comment by CatAndHorse** [comment]
if I use robot to put marker Tile itdoesn't work

**Comment by jurgyy** [comment]
Fixed in 1.1.16 https://github.com/jurgyy/Factorio-Canal-Excavator/releases/tag/v1.1.6

Let me know if you encounter any other problems!

**Comment by CatAndHorse** [comment]
i tried new version,but now Excavatable Surface (stone ore) generated when i use repair turret build vanilla landfill or any floor (tile)
