### ISSUE TITLE
1.16 version, now Excavatable Surface (stone ore) also generated when i use repair turret build vanilla landfill or any floor (tile)

### ISSUE THREAD

**Issue by CatAndHorse** [jurgyy/Factorio-Canal-Excavator#3]

**Comment by jurgyy** [comment]
Fixed in [1.17](https://github.com/jurgyy/Factorio-Canal-Excavator/releases/tag/v1.1.7). Though there's still a bug when the tiles get removed by script leaving the ore behind. I have requested a modding interface on the Factorio forums in the hope that Wubes makes this easier to fix.
