### ISSUE TITLE
this exception raise when I build sone_path tile onto a tile has already been dug using repair turret

### ISSUE THREAD

**Issue by CatAndHorse** [jurgyy/Factorio-Canal-Excavator#4]
Error while running event canal-excavator::script_raised_set_tiles (ID 83)
Unknown item name: stone-path
stack traceback:
	[C]: in function 'spill_item_stack'
	__canal-excavator__/events/placeTileEvent.lua:56: in function 'undo_set_tile'
	__canal-excavator__/events/placeTileEvent.lua:121: in function 'place_tile_as_script'
	__canal-excavator__/events/placeTileEvent.lua:168: in function <__canal-excavator__/events/placeTileEvent.lua:162>
stack traceback:
	[C]: in function 'revive'
	__Repair_Turret__/script/repair_turret.lua:615: in function 'build_entity'
	__Repair_Turret__/script/repair_turret.lua:779: in function 'update_turret'
	__Repair_Turret__/script/repair_turret.lua:888: in function 'check_turret_update'
	__Repair_Turret__/script/repair_turret.lua:991: in function 'handler'
	__core__/lualib/event_handler.lua:47: in function <__core__/lualib/event_handler.lua:45>

**Comment by jurgyy** [comment]
I've just released 1.17, could you verify if the bug still persists?

**Comment by CatAndHorse** [comment]
It won't crash in 1.17 now.
And i Can dig the left behind ore up myself use excavator.
